[mypy]
python_version = 3.12

[mypy-plotly]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True

[mypy-numpy]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-nicegui]
ignore_missing_imports = True

[mypy-nicegui.*]
ignore_missing_imports = True
